/// Flutter icons ManagerIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ManagerIcons
///      fonts:
///       - asset: fonts/ManagerIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ManagerIcons {
  ManagerIcons._();

  static const _kFontFam = 'ManagerIcons';
  static const String? _kFontPkg = null;

  static const IconData market = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menuCustom = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
